import { apiClient } from '../../../shared/api/apiClient';
import {
  Reward,
  RewardEligibilityResponse,
  RewardApplyInput,
} from '../types';

/**
 * Reward configuration interface
 */
export interface RewardConfig {
  attendance_threshold: number;
  discount_percentage: number;
  expiration_days: number;
  eligible_plan_units: string[];
}

/**
 * API endpoints for rewards feature
 */
const REWARDS_ENDPOINTS = {
  calculateEligibility: (subscriptionId: string) => `/subscriptions/${subscriptionId}/rewards/calculate`,
  getAvailableRewards: (clientId: string) => `/clients/${clientId}/rewards/available`,
  getRewardsBySubscription: (subscriptionId: string) => `/subscriptions/${subscriptionId}/rewards`,
  applyReward: (rewardId: string) => `/rewards/${rewardId}/apply`,
  getConfig: () => '/rewards/config',
} as const;

/**
 * Rewards API client
 * Provides methods to interact with rewards endpoints
 */
export const rewardsApi = {
  /**
   * Calculate eligibility for a subscription
   * Counts attendances in the subscription cycle and creates reward if eligible
   */
  async calculateEligibility(subscriptionId: string): Promise<RewardEligibilityResponse> {
    return apiClient.post<RewardEligibilityResponse>(
      REWARDS_ENDPOINTS.calculateEligibility(subscriptionId)
    );
  },

  /**
   * Get available rewards for a client
   * Returns rewards with status='pending' that haven't expired
   */
  async getAvailableRewards(clientId: string): Promise<Reward[]> {
    return apiClient.get<Reward[]>(REWARDS_ENDPOINTS.getAvailableRewards(clientId));
  },

  /**
   * Get all rewards for a subscription
   * Returns all rewards (pending, applied, expired) generated by a subscription
   */
  async getRewardsBySubscription(subscriptionId: string): Promise<Reward[]> {
    return apiClient.get<Reward[]>(REWARDS_ENDPOINTS.getRewardsBySubscription(subscriptionId));
  },

  /**
   * Apply a reward to a subscription
   * Marks the reward as applied and associates it with the subscription
   */
  async applyReward(rewardId: string, data: RewardApplyInput): Promise<Reward> {
    return apiClient.post<Reward>(REWARDS_ENDPOINTS.applyReward(rewardId), data);
  },

  /**
   * Get reward system configuration
   * Returns the current reward configuration (threshold, discount, expiration, eligible plans)
   * This endpoint is public and does not require authentication
   */
  async getRewardConfig(): Promise<RewardConfig> {
    return apiClient.get<RewardConfig>(REWARDS_ENDPOINTS.getConfig());
  },
};

